repos:
  -   repo: https://github.com/PyCQA/flake8
      rev: 7.1.1
      hooks:
       - id: flake8

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.12.1
    hooks:
      - id: mypy
        additional_dependencies: [mypy]
